# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  GO111MODULE: 'on' # enable Go modules
  modulePath: '$(GOPATH)/src/go.bobheadxi.dev/zapx' # Path to the module's code

steps:
- task: GoTool@0
  inputs:
    version: '1.12'

- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    go version
  displayName: 'Set up the Go workspace'

- script: |
    make mod
    go get -u golang.org/x/lint/golint
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies'

- script: make lint
  workingDirectory: '$(modulePath)'
  displayName: 'Run static analysis'

- script: make test TEST_FLAGS="-v -race -coverprofile=coverage.txt"
  workingDirectory: '$(modulePath)'
  displayName: 'Run tests and report coverage'

- script: make codecov CODECOV_TOKEN=$(CODECOV_TOKEN)
  workingDirectory: '$(modulePath)'
  displayName: 'Report coverage'
  condition: succeeded()
