name: Benchmark
on:
  push:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: gobenchdata to gh-pages
      uses: bobheadxi/gobenchdata@master
      with:
        SUBDIRECTORY: ./benchmarks
        PRUNE_COUNT: 20
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
